(function(){
  const config=window.PORTAL_CONFIG,$=(s,r=document)=>r.querySelector(s);
  const isProjector=new URLSearchParams(location.search).get('projector')==='1';
  const projectionChannel='BroadcastChannel' in window?new BroadcastChannel('infs5706-w7-presentation'):null;
  const releaseBanner=index=>`<div class="release-banner"><div><span>Phase ${index+1}</span><strong>${config.phases[index].label}</strong><small>${config.phases[index].minutes} minutes</small></div><div class="release-code"><span>Enter code</span><strong>${config.phases[index].code||'OPEN'}</strong></div></div>`;
  const phaseSlide=(index,title,task,output,theme='')=>({theme,title,html:`${releaseBanner(index)}<h2>${title}</h2><div class="launch-copy"><p><strong>Do</strong>${task}</p><p><strong>Produce</strong>${output}</p></div><p class="portal-cue">Detailed instructions and fields are in your student portal.</p>`});
  const checkpoint=()=>'<div class="checkpoint-banner"><span>Debrief and Share checkpoint</span><strong>Pause your portal work and rejoin the class.</strong></div>';
  const slides=[
    {theme:'yellow intro-journey',title:'Today’s seminar journey',html:'<div class="eyebrow">Week 7 · Simple Agents</div><h1>From judgement to a working agent</h1><div class="journey-map"><div><b>1</b><span>Decide authority</span></div><div><b>2</b><span>Observe an agent</span></div><div><b>3</b><span>Classify AskTelstra</span></div><div><b>4</b><span>Design</span></div><div><b>5</b><span>Write instructions</span></div><div><b>6</b><span>Build and run</span></div><div><b>7</b><span>Challenge and refine</span></div><div><b>8</b><span>Defend and submit</span></div></div><div class="groundrules"><strong>How we will work</strong><ul><li><b>One laptop per team:</b> nominate one recorder.</li><li><b>Assign roles:</b> evidence, design, builder and challenger.</li><li><b>Everyone participates:</b> discuss, test and defend together.</li><li><b>Watch the timer:</b> move on when each checkpoint closes.</li><li><b>Use synthetic information only.</b></li><li><b>Before leaving:</b> submit one team Word record.</li></ul></div>'},
    phaseSlide(0,'Would you let an agent do this before coffee?','Classify each action as Act, Check or Stop.','One reason why your team’s level of authority changed.','yellow'),
    {title:'Authority debrief',html:`${checkpoint()}<h2>What changed across your decisions?</h2><ul><li>What could go wrong?</li><li>Could the action be reversed?</li><li>What information would the agent need?</li><li>Who has authority to decide?</li></ul><p><strong>When should an agent act, prepare something for review or stop?</strong></p>`},
    phaseSlide(1,'Watch a simple agent work','Observe the modelled run from goal through to human hand-off.','One behaviour that makes the system agentic.','dark'),
    {title:'Demonstration debrief',html:`${checkpoint()}<h2>What made the experience agentic?</h2><p class="debrief-question">What did the system manage across the task, and what responsibility remained with a person?</p><p><strong>One or two teams:</strong> share one observed behaviour, then name the boundary.</p>`},
    phaseSlide(2,'Use evidence to classify AskTelstra','Examine what has been reported and what remains unestablished.','A classification supported by evidence and one evidence gap.'),
    {title:'AskTelstra evidence discussion',html:`${checkpoint()}<h2>What can the available evidence support?</h2><p class="debrief-question">Would you classify current AskTelstra as a search tool, AI assistant, bounded agent or autonomous service system?</p><p><strong>Be ready to identify the evidence you used and one claim the evidence cannot establish.</strong></p>`},
    phaseSlide(3,'Design before you build','Complete the eight design decisions for your allocated customer scenario.','One coherent, bounded agent design.','yellow'),
    {theme:'dark',title:'Break',html:'<h1>Break</h1><p class="debrief-question">Return in 10 minutes.</p><p>Next: turn your design into instructions and configure the agent.</p>'},
    phaseSlide(4,'Turn the design into instructions','Find and revise the weakness most likely to affect behaviour. Complete the pre-build quality gate.','One checked instruction set ready to configure.'),
    phaseSlide(5,'Configure and run','Build the agent and run the representative synthetic case.','Evidence of what worked, what failed and what the agent produced.','yellow'),
    phaseSlide(6,'Challenge and refine','Run the challenge variation, revise one instruction and rerun it.','Evidence showing whether the revision changed the behaviour.','dark'),
    phaseSlide(7,'Show, tell and defend','Every team submits. Selected teams give a 60-second evidence-based defence.','A submitted Word record and a defensible retain, revise or reject decision.')
  ];
  const auth=$('#auth');if(sessionStorage.getItem('w7-facilitator')==='yes'||isProjector)auth.hidden=true;
  if(isProjector)document.body.classList.add('projector-mode');
  $('#authForm').addEventListener('submit',e=>{e.preventDefault();if($('#passcode').value===window.FACILITATOR_DATA.passcode){sessionStorage.setItem('w7-facilitator','yes');auth.hidden=true;}else $('#authError').textContent='Incorrect passcode.';});
  let index=Math.max(0,Math.min(slides.length-1,Number(location.hash.slice(1))||0));
  function notify(message){projectionChannel?.postMessage(message);if(window.opener&&!window.opener.closed)window.opener.postMessage({source:'w7-projector',...message},location.origin);}
  function render(){const s=slides[index];$('#slide').className=`slide ${s.theme||''}`;$('#slide').innerHTML=s.html;$('#slideTitle').textContent=s.title;$('#slideNumber').textContent=`${index+1} / ${slides.length}`;$('#prev').disabled=index===0;$('#next').disabled=index===slides.length-1;history.replaceState(null,'',`${location.pathname}${location.search}#${index}`);scrollTo(0,0);$('#slide').scrollTop=0;notify({type:'slideChanged',index});}
  function renderTimer(timer={}){const phase=timer.phase||'Authority warm-up',phaseNumber=timer.phaseNumber||'Phase 1 of 8',clock=timer.clock||'10:00',status=timer.status||'Ready or paused';$('#projectorPhaseNumber').textContent=phaseNumber;$('#projectorPhase').textContent=phase;$('#projectorClock').textContent=clock;$('#projectorTimerStatus').textContent=status;$('#projectorInstruction').textContent=timer.instruction||'';$('#chipPhase').textContent=`${phaseNumber.replace(' of 8','')} · ${phase}`;$('#chipClock').textContent=clock;$('#chipStatus').textContent=status;}
  function setMode(mode,timer){const showTimer=mode==='timer';$('#projectorTimer').hidden=!showTimer;$('.present-shell').hidden=showTimer;$('#projectorClockChip').hidden=showTimer||!isProjector;if(timer)renderTimer(timer);}
  function receive(message){if(!message)return;if(message.type==='ping')notify({type:'ready'});if(message.type==='state'){index=Math.max(0,Math.min(slides.length-1,Number(message.slide)||0));render();setMode(message.mode,message.timer);}if(message.type==='slide'){index=Math.max(0,Math.min(slides.length-1,Number(message.index)||0));render();setMode('slides');}if(message.type==='mode')setMode(message.mode,message.timer);if(message.type==='timer')renderTimer(message.timer);}
  projectionChannel&&(projectionChannel.onmessage=e=>receive(e.data));
  addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.source==='w7-facilitator')receive(e.data);});
  $('#prev').addEventListener('click',()=>{if(index>0){index--;render();}});$('#next').addEventListener('click',()=>{if(index<slides.length-1){index++;render();}});$('#fullScreen').addEventListener('click',()=>document.documentElement.requestFullscreen?.());addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)&&index<slides.length-1){index++;render();}if(['ArrowLeft','PageUp'].includes(e.key)&&index>0){index--;render();}});addEventListener('beforeunload',()=>isProjector&&notify({type:'closing'}));render();if(isProjector){setMode('slides');notify({type:'ready'});}
})();
